package se.capeit.dev.containercloud.feature;

public final class RunInContainerCloudConstants {
    public static final String TYPE = "RunInContainerCloud";
    public static final String FeatureSettingsJspFile = "feature-settings.jsp";
    public static final String FeatureSettingsHtmlFile = "feature-settings.html";

    public static final String ParameterName_CloudProfile = "CloudProfile";
    public static final String ParameterName_Image = "Image";

    // This regular expression validates a container image, source: https://github.com/docker/distribution/blob/master/reference/regexp.go
    // The expression corresponds to what would be generated by the code anchored(NameRegexp, literal(":"), TagRegexp)
    public static final String ContainerImageRegex = "^(?:(?:[a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9-]*[a-zA-Z0-9])(?:(?:\\.(?:[a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9-]*[a-zA-Z0-9]))+)?(?::[0-9]+)?/)?[a-z0-9]+(?:(?:(?:[._]|__|[-]*)[a-z0-9]+)+)?(?:(?:/[a-z0-9]+(?:(?:(?:[._]|__|[-]*)[a-z0-9]+)+)?)+)?:[\\w][\\w.-]{0,127}$";

    // JSP getters
    public String getParameterName_CloudProfile() {
        return ParameterName_CloudProfile;
    }

    public String getParameterName_Image() {
        return ParameterName_Image;
    }
}
